#!/bin/bash
# context-reset.sh - Handle context reset events (/clear, /compact)
# Generated by /s2s:init
# Version: 1.1.0
#
# Hook for SessionStart event - detects context resets and handles token tracking.
#
# Behavior:
#   - On /clear: Reset token tracking, suggest resume command
#   - On /compact: Reset token baseline, suggest resume command
#   - On autocompact (experimental): Auto-continue roundtable if enabled
#
# Configuration:
#   Add to .claude/settings.json:
#   {
#     "hooks": {
#       "SessionStart": [{
#         "hooks": [{
#           "type": "command",
#           "command": ".claude/context-reset.sh"
#         }]
#       }]
#     }
#   }

INPUT=$(cat)

# Get project directory from input
PROJECT_DIR=$(echo "$INPUT" | jq -r '.cwd // "."')
S2S_DIR="${PROJECT_DIR}/.s2s"

# Check if this is an s2s project
if [[ ! -d "$S2S_DIR" ]]; then
    exit 0
fi

# Parse event details
SOURCE=$(echo "$INPUT" | jq -r '.source // "startup"')
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // ""')

# Only handle clear and compact events
if [[ "$SOURCE" != "clear" && "$SOURCE" != "compact" ]]; then
    exit 0
fi

# Check for active roundtable session
STATE_FILE="${S2S_DIR}/state.json"
ACTIVE_SESSION=""
WORKFLOW_TYPE=""
RT_SESSION_ID=""
RT_ROUND=""

if [[ -f "$STATE_FILE" ]]; then
    ACTIVE_SESSION=$(jq -r '.active_session // empty' "$STATE_FILE" 2>/dev/null)
    if [[ -n "$ACTIVE_SESSION" && "$ACTIVE_SESSION" != "null" ]]; then
        WORKFLOW_TYPE=$(jq -r '.active_session.workflow_type // ""' "$STATE_FILE" 2>/dev/null)
        RT_SESSION_ID=$(jq -r '.active_session.id // ""' "$STATE_FILE" 2>/dev/null)
        RT_ROUND=$(jq -r '.active_session.round // 0' "$STATE_FILE" 2>/dev/null)
    fi
fi

# Get actual current token count from context-window.json (written by statusline)
# Note: Statusline runs AFTER this hook, so values may be from before clear/compact.
# The token-tracker init on resume will capture fresh values and correct any discrepancy.
CONTEXT_FILE="${S2S_DIR}/context-window.json"
CURRENT_TOKENS=0
CURRENT_PCT=0
VALUES_STALE=false

if [[ -f "$CONTEXT_FILE" ]]; then
    # Check if file is recent (within last 2 seconds) - might be stale
    FILE_AGE=$(( $(date +%s) - $(stat -f %m "$CONTEXT_FILE" 2>/dev/null || stat -c %Y "$CONTEXT_FILE" 2>/dev/null || echo 0) ))
    if [[ $FILE_AGE -gt 2 ]]; then
        VALUES_STALE=true
    fi

    # Read values (may be stale but better than nothing)
    USED_PCT=$(jq -r '.used_percentage // 0' "$CONTEXT_FILE" 2>/dev/null)
    CTX_SIZE=$(jq -r '.context_window_size // 200000' "$CONTEXT_FILE" 2>/dev/null)

    if [[ -n "$USED_PCT" && "$USED_PCT" != "null" ]]; then
        # Calculate actual tokens from percentage
        CURRENT_TOKENS=$(awk "BEGIN {printf \"%.0f\", $CTX_SIZE * $USED_PCT / 100}")
        CURRENT_PCT=$(awk "BEGIN {printf \"%.0f\", $USED_PCT}")
    fi
fi

# Reset token tracking cache if roundtable was active
if [[ -n "$RT_SESSION_ID" ]]; then
    CACHE_FILE="${S2S_DIR}/sessions/${RT_SESSION_ID}.cache"

    if [[ -f "$CACHE_FILE" ]]; then
        # Read current values to preserve session-level data
        ROUNDS_DELTA_ACCUM=$(grep "^roundsDeltaAccum=" "$CACHE_FILE" 2>/dev/null | cut -d= -f2)
        ROUNDS_DELTA_ACCUM=${ROUNDS_DELTA_ACCUM:-0}

        if [[ "$SOURCE" == "clear" ]]; then
            # Full reset - update baseline to actual current tokens (not zero)
            echo "contextCleared=true" >> "$CACHE_FILE"
            echo "clearedAt=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$CACHE_FILE"
            # Set session start to actual current tokens (preloaded context)
            sed -i.bak "s/^sessionStartTokens=.*/sessionStartTokens=${CURRENT_TOKENS}/" "$CACHE_FILE" 2>/dev/null || \
                sed -i '' "s/^sessionStartTokens=.*/sessionStartTokens=${CURRENT_TOKENS}/" "$CACHE_FILE"
            sed -i.bak "s/^lastT3=.*/lastT3=${CURRENT_TOKENS}/" "$CACHE_FILE" 2>/dev/null || \
                sed -i '' "s/^lastT3=.*/lastT3=${CURRENT_TOKENS}/" "$CACHE_FILE"
            rm -f "${CACHE_FILE}.bak" 2>/dev/null
        else
            # Compact - update baseline to actual current tokens
            echo "compactOccurred=true" >> "$CACHE_FILE"
            echo "compactedAt=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$CACHE_FILE"
            # Set lastT3 to actual current tokens so next round gap is accurate
            sed -i.bak "s/^lastT3=.*/lastT3=${CURRENT_TOKENS}/" "$CACHE_FILE" 2>/dev/null || \
                sed -i '' "s/^lastT3=.*/lastT3=${CURRENT_TOKENS}/" "$CACHE_FILE"
            rm -f "${CACHE_FILE}.bak" 2>/dev/null
        fi
    fi
fi

# Update state.json to mark the event
if [[ -f "$STATE_FILE" ]]; then
    TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

    # Read current state to preserve active_plan
    ACTIVE_PLAN=$(jq -r '.active_plan // null' "$STATE_FILE" 2>/dev/null)

    # Update last_activity with context event
    jq --arg action "context_${SOURCE}" \
       --arg timestamp "$TIMESTAMP" \
       --arg session_id "$RT_SESSION_ID" \
       '.last_activity = {
         "timestamp": $timestamp,
         "action": $action,
         "session_id": (if $session_id == "" then null else $session_id end)
       }' "$STATE_FILE" > "${STATE_FILE}.tmp" && mv "${STATE_FILE}.tmp" "$STATE_FILE"
fi

# Calculate display values
CURRENT_K=$((CURRENT_TOKENS / 1000))
STALE_NOTE=""
if [[ "$VALUES_STALE" == "true" ]]; then
    STALE_NOTE=" (will refresh on resume)"
fi

# Output message for user
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if [[ "$SOURCE" == "clear" ]]; then
    echo "  Context cleared - baseline: ${CURRENT_K}k tokens (${CURRENT_PCT}%)${STALE_NOTE}"
else
    echo "  Context compacted - baseline: ${CURRENT_K}k tokens (${CURRENT_PCT}%)${STALE_NOTE}"
fi

# If roundtable was active, show resume command
if [[ -n "$WORKFLOW_TYPE" && -n "$RT_SESSION_ID" ]]; then
    echo ""
    echo "  Active roundtable interrupted:"
    echo "    Workflow: ${WORKFLOW_TYPE}"
    echo "    Session:  ${RT_SESSION_ID}"
    echo "    Round:    ${RT_ROUND} completed"
    echo ""
    echo "  To resume, run:"
    echo ""
    echo "    /s2s:${WORKFLOW_TYPE} --session ${RT_SESSION_ID}"
    echo ""
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

exit 0
