#!/bin/bash
# context-reset.sh - Handle context reset events (/clear, /compact)
# Generated by /s2s:init
# Version: 2.3.0 - BUG-024: no-jq fallback scoped to the active_session block
#
# Hook for SessionStart event - detects context resets.
#
# Behavior:
#   - Updates state.json with last_activity (requires jq)
#   - Shows resume command if roundtable was interrupted
#
# Dependencies:
#   - jq (recommended): Full functionality including state.json updates
#   - Without jq: Core functionality works, state.json update skipped
#
# Configuration:
#   Add to .claude/settings.json:
#   {
#     "hooks": {
#       "SessionStart": [{
#         "hooks": [{
#           "type": "command",
#           "command": ".claude/context-reset.sh"
#         }]
#       }]
#     }
#   }

INPUT=$(cat)

# Check jq availability
if command -v jq &>/dev/null; then
    HAS_JQ=true
else
    HAS_JQ=false
fi

# Helper: extract value from flat JSON using grep/sed (fallback when no jq)
# Usage: json_extract "key" "$json_string"
# Tolerates optional whitespace after the colon ("key": "value") so it works on
# both compact hook input and pretty-printed files (jq always emits ": ").
json_extract() {
    local key="$1"
    local json="$2"
    echo "$json" | grep -oE "\"${key}\": *\"[^\"]*\"" | head -1 | cut -d'"' -f4
}

# Get project directory from input
if [[ "$HAS_JQ" == "true" ]]; then
    PROJECT_DIR=$(echo "$INPUT" | jq -r '.cwd // "."')
else
    PROJECT_DIR=$(json_extract "cwd" "$INPUT")
    PROJECT_DIR=${PROJECT_DIR:-.}
fi

S2S_DIR="${PROJECT_DIR}/.s2s"
STATE_FILE="${S2S_DIR}/state.json"

# Check if this is an s2s project
[[ ! -d "$S2S_DIR" ]] && exit 0
[[ ! -f "$STATE_FILE" ]] && exit 0

# Parse event source
if [[ "$HAS_JQ" == "true" ]]; then
    SOURCE=$(echo "$INPUT" | jq -r '.source // "startup"')
else
    SOURCE=$(json_extract "source" "$INPUT")
    SOURCE=${SOURCE:-startup}
fi

# Only handle clear and compact events
[[ "$SOURCE" != "clear" && "$SOURCE" != "compact" ]] && exit 0

# Get active session info (if any)
if [[ "$HAS_JQ" == "true" ]]; then
    WORKFLOW_TYPE=$(jq -r '.active_session.workflow_type // ""' "$STATE_FILE" 2>/dev/null)
    RT_SESSION_ID=$(jq -r '.active_session.id // ""' "$STATE_FILE" 2>/dev/null)
    RT_ROUND=$(jq -r '.active_session.round // 0' "$STATE_FILE" 2>/dev/null)
else
    # BUG-024: scope the fallback to the active_session block. The old file-wide
    # grep matched the FIRST "workflow_type"/"id"/"round" anywhere in state.json
    # (e.g. a history or last_activity entry), which could aim the resume
    # command at the wrong session. Flatten newlines so the regex spans
    # pretty-printed JSON; active_session is a flat object, so the first "}"
    # closes it. If the block cannot be isolated, leave the fields empty (no
    # banner) rather than guess from unscoped matches.
    AS_BLOCK=$(tr '\n' ' ' < "$STATE_FILE" 2>/dev/null | grep -oE '"active_session"[[:space:]]*:[[:space:]]*\{[^{}]*\}' | head -1)
    WORKFLOW_TYPE=$(json_extract "workflow_type" "$AS_BLOCK")
    RT_SESSION_ID=$(json_extract "id" "$AS_BLOCK")
    RT_ROUND=$(echo "$AS_BLOCK" | grep -oE '"round": *[0-9]+' | head -1 | sed -E 's/.*: *//')
    RT_ROUND=${RT_ROUND:-0}
fi

# Update state.json with last_activity (only if jq available)
if [[ "$HAS_JQ" == "true" ]]; then
    TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    jq --arg action "context_${SOURCE}" \
       --arg timestamp "$TIMESTAMP" \
       --arg session_id "$RT_SESSION_ID" \
       '.last_activity = {
         "timestamp": $timestamp,
         "action": $action,
         "session_id": (if $session_id == "" then null else $session_id end)
       }' "$STATE_FILE" > "${STATE_FILE}.tmp" && mv "${STATE_FILE}.tmp" "$STATE_FILE"
fi

# Show resume command if roundtable was active
if [[ -n "$WORKFLOW_TYPE" && -n "$RT_SESSION_ID" ]]; then
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  Roundtable interrupted by /${SOURCE}"
    echo ""
    echo "    Workflow: ${WORKFLOW_TYPE}"
    echo "    Session:  ${RT_SESSION_ID}"
    echo "    Round:    ${RT_ROUND} completed"
    echo ""
    echo "  To resume:"
    echo "    /s2s:${WORKFLOW_TYPE} --session ${RT_SESSION_ID}"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
fi

# Show warning if jq not available
if [[ "$HAS_JQ" != "true" ]]; then
    echo ""
    echo "  Note: 'jq' not found. Install jq for full functionality."
    echo "    macOS:   brew install jq"
    echo "    Linux:   apt install jq  (or equivalent)"
    echo "    Windows: choco install jq  (or download from https://jqlang.github.io/jq/)"
    echo ""
fi

exit 0
