#!/bin/bash
# context-reset.sh - Handle context reset events (/clear, /compact)
# Generated by /s2s:init
# Version: 2.0.0
#
# Hook for SessionStart event - detects context resets.
#
# Behavior:
#   - Updates state.json with last_activity
#   - Shows resume command if roundtable was interrupted
#
# Configuration:
#   Add to .claude/settings.json:
#   {
#     "hooks": {
#       "SessionStart": [{
#         "hooks": [{
#           "type": "command",
#           "command": ".claude/context-reset.sh"
#         }]
#       }]
#     }
#   }

INPUT=$(cat)

# Get project directory from input
PROJECT_DIR=$(echo "$INPUT" | jq -r '.cwd // "."')
S2S_DIR="${PROJECT_DIR}/.s2s"
STATE_FILE="${S2S_DIR}/state.json"

# Check if this is an s2s project
[[ ! -d "$S2S_DIR" ]] && exit 0
[[ ! -f "$STATE_FILE" ]] && exit 0

# Parse event details
SOURCE=$(echo "$INPUT" | jq -r '.source // "startup"')

# Only handle clear and compact events
[[ "$SOURCE" != "clear" && "$SOURCE" != "compact" ]] && exit 0

# Get active session info (if any)
WORKFLOW_TYPE=$(jq -r '.active_session.workflow_type // ""' "$STATE_FILE" 2>/dev/null)
RT_SESSION_ID=$(jq -r '.active_session.id // ""' "$STATE_FILE" 2>/dev/null)
RT_ROUND=$(jq -r '.active_session.round // 0' "$STATE_FILE" 2>/dev/null)

# Update state.json with last_activity
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
jq --arg action "context_${SOURCE}" \
   --arg timestamp "$TIMESTAMP" \
   --arg session_id "$RT_SESSION_ID" \
   '.last_activity = {
     "timestamp": $timestamp,
     "action": $action,
     "session_id": (if $session_id == "" then null else $session_id end)
   }' "$STATE_FILE" > "${STATE_FILE}.tmp" && mv "${STATE_FILE}.tmp" "$STATE_FILE"

# Show resume command if roundtable was active
if [[ -n "$WORKFLOW_TYPE" && -n "$RT_SESSION_ID" ]]; then
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  Roundtable interrupted by /${SOURCE}"
    echo ""
    echo "    Workflow: ${WORKFLOW_TYPE}"
    echo "    Session:  ${RT_SESSION_ID}"
    echo "    Round:    ${RT_ROUND} completed"
    echo ""
    echo "  To resume:"
    echo "    /s2s:${WORKFLOW_TYPE} --session ${RT_SESSION_ID}"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
fi

exit 0
