#!/bin/bash
# s2s statusline - Token tracking with chain to user's global statusline
# Generated by /s2s:init
# Version: 2.1.0
#
# Writes session-specific context data to temp directory for token tracking.
# Each CC session gets its own file, avoiding conflicts between parallel sessions.

INPUT=$(cat)

# === S2S Token Tracking ===
# Extract session_id for session isolation
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // "unknown"')

# Use temp directory (CLAUDE_CODE_TMPDIR if set, otherwise system temp)
S2S_TMPDIR="${CLAUDE_CODE_TMPDIR:-${TMPDIR:-/tmp}}"

# Save context_window + session_id to session-specific file
echo "$INPUT" | jq '{
  session_id: .session_id,
  used_percentage: .context_window.used_percentage,
  remaining_percentage: .context_window.remaining_percentage,
  total_input_tokens: .context_window.total_input_tokens,
  context_window_size: .context_window.context_window_size
}' > "$S2S_TMPDIR/s2s-context-window-${SESSION_ID}.json" 2>/dev/null

# === Chain to User's Global Statusline ===
# Read the command path from global settings (not hardcoded)
GLOBAL_SETTINGS="$HOME/.claude/settings.json"
GLOBAL_STATUSLINE=""

if [[ -f "$GLOBAL_SETTINGS" ]]; then
    GLOBAL_STATUSLINE=$(jq -r '.statusLine.command // empty' "$GLOBAL_SETTINGS" 2>/dev/null)
fi

if [[ -n "$GLOBAL_STATUSLINE" && -x "$GLOBAL_STATUSLINE" ]]; then
    # User has a global statusline - chain to it for display
    echo "$INPUT" | "$GLOBAL_STATUSLINE"
else
    # Fallback: minimal statusline with context info
    MODEL=$(echo "$INPUT" | jq -r '.model.display_name // "Claude"')
    DIR=$(echo "$INPUT" | jq -r '.workspace.current_dir // "."')
    DIR_NAME=$(basename "$DIR")
    PCT=$(echo "$INPUT" | jq -r '.context_window.used_percentage // 0' | awk '{printf "%.0f", $1}')

    # Git branch if available
    BRANCH=""
    if git rev-parse --git-dir > /dev/null 2>&1; then
        BRANCH=$(git branch --show-current 2>/dev/null)
        [[ -n "$BRANCH" ]] && BRANCH=" on \033[33m$BRANCH\033[0m"
    fi

    # Color code context percentage
    if [[ $PCT -lt 60 ]]; then
        PCT_COLOR="\033[32m"  # Green
    elif [[ $PCT -lt 80 ]]; then
        PCT_COLOR="\033[33m"  # Yellow
    else
        PCT_COLOR="\033[31m"  # Red
    fi

    printf "\033[1m%s\033[0m in \033[36m%s\033[0m%b | ${PCT_COLOR}%s%%\033[0m\n" "$MODEL" "$DIR_NAME" "$BRANCH" "$PCT"
fi
